name: Actions workflow
on: 
  push:
    branches:
      - "main"
  pull_request:
    types:
      - "closed"
      - "assigned"
      - "opened"
      - "closed"
      - "assigned"
    branches:
      - "main/*" # matches branch like main wild
#  schedule:
    # - cron: "* * * * *" # min hr day mon day https://crontab.guru/#
  # repository_dispatch:
    # send a post req to a url and use the requests name to trigger the repodisp action


jobs:
  run-git-actions:
    runs-on: ubuntu-latest
    steps:
      - name: lsfs
        run: |
          pwd
          ls -a
      - name: simple js Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Shay
      - name: greeting log
        run: echo "${{steps.greet.outputs.time}}"
