name: decrpytor
on: push
jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - name: decrpytor
        run: |
          ls -a
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.json Secretkey.txt
          ls -a
      - name: print file
        run: cat $HOME/secret.txt
        env:
          passp: ${{secrets.PASSPHRASE}}

