name: run python cmds
on: [push]
jobs:
  run-shell-cmds:
    runs-on: ubuntu-latest
    steps:
      - name: python command
        run: |
          import platform
          print (platform.processor())
          print(f'The sum of 2 + 3 = { 2 + 3}')
        shell: python